"""empty message

Revision ID: 8dc29e3d2fff
Revises: 6819e2f9f626
Create Date: 2023-12-30 07:45:44.954357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc29e3d2fff'
down_revision = '6819e2f9f626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('reply',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('reply',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)

    # ### end Alembic commands ###
