"""empty message

Revision ID: 908c23e196af
Revises: ac5f721d26ca
Create Date: 2023-12-30 23:43:47.092530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908c23e196af'
down_revision = 'ac5f721d26ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_next_date'), ['next_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_next_date'))
        batch_op.drop_column('next_date')

    # ### end Alembic commands ###
